---

- name: NEXUS | Manage user
  import_tasks: users.yml

- name: NEXUS | Manage system limits
  lineinfile:
    path: /etc/security/limits.conf
    line: "nexus           -       nofile          65536"
    state: present

- name: NEXUS | Manage pam.d on Ubuntu server
  lineinfile:
    path: /etc/pam.d/common-session
    line: "session required        pam_limits.so"
    state: present

- name: NEXUS | Unarchive sources
  unarchive:
    src: "{{ nexus_source_url }}"
    dest: "{{ nexus_install_dir }}"
    owner: "{{ nexus_user }}"
    group: "{{ nexus_group }}"
    remote_src: yes

- name: NEXUS | Find sources directory
  find:
    path: "{{ nexus_install_dir }}"
    patterns: "nexus-*"
    file_type: directory
  register: installed_dir

- name: NEXUS | Versioned directory
  set_fact:
    nexus_versioned_dir: "{{ installed_dir.files[installed_dir.matched-1].path }}"

- name: NEXUS | Create symlink
  file:
    state: link
    src: "{{ nexus_versioned_dir }}"
    dest: "{{ nexus_workdir }}"
    owner: "{{ nexus_user }}"
    group: "{{ nexus_group }}"

- name: NEXUS | Ensure user is owner of directory
  file:
    path: "{{ nexus_versioned_dir }}"
    owner: "{{ nexus_user }}"
    group: "{{ nexus_group }}"
    recurse: yes

- name: NEXUS | Ensure user is owner of sonatype-work
  file:
    path: "{{ nexus_install_dir }}/sonatype-work"
    owner: "{{ nexus_user }}"
    group: "{{ nexus_group }}"
    recurse: yes

- name: NEXUS | Uncomment run_as_user
  lineinfile:
    dest: "{{ nexus_workdir }}/bin/nexus.rc"
    regexp: "^#run_as_user="
    line: "run_as_user={{ nexus_user }}"
    backrefs: yes

- name: NEXUS | Configure NEXUS_HOME
  lineinfile:
    dest: "/etc/environment"
    line: "NEXUS_HOME={{ nexus_workdir }}"
    state: present

- name: NEXUS | Manage logs
  import_tasks: logs.yml

- name: NEXUS | Manage Systemd
  import_tasks: systemd.yml
